CREATE TABLE CARS(
S_NO INT(5),
CUSTOMER_NAME VARCHAR(100),
CAR_COMPANY VARCHAR(100),
CAR_MODEL VARCHAR(100),
COST_OF_PURCHASE DOUBLE(30,0),
DATE_OF_PURCHASE DATE,
PHONE_NO VARCHAR(14),
ADDRESS VARCHAR(500));
 