import java.awt.Color;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Balaji
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
           Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);

    }

    public void sound()
    {
        try {
            InputStream in = new FileInputStream("build\\classes\\car_0003.wav");
            AudioStream as = new AudioStream(in);
            AudioPlayer.player.start(as);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        Company_Combo = new javax.swing.JComboBox();
        Car_Model_Combo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Data_Addition = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Main_Menu = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(979, 843));
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel1.setText("Customer Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 60, 126, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setText("Customer Phone No.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 130, 163, 22);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18));
        getContentPane().add(jTextField1);
        jTextField1.setBounds(240, 50, 250, 40);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18));
        getContentPane().add(jTextField2);
        jTextField2.setBounds(240, 120, 250, 40);

        Company_Combo.setFont(new java.awt.Font("Times New Roman", 0, 24));
        Company_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Company", "Aston Martin", "Audi", "BMW", "Cadillac", "Chevrolet", "Dodge", "Fiat", "Ford", "Lamborghini", "Lexus", "Lotus", "Mazda", "Mercedec-Benz", "Mitsubishi Motors", "Pontiac", "Porshe", "Renault", "Subaru", "Toyota", "Vauxhall", "Volkswagon" }));
        Company_Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Company_ComboActionPerformed(evt);
            }
        });
        getContentPane().add(Company_Combo);
        Company_Combo.setBounds(560, 50, 370, 50);

        Car_Model_Combo.setFont(new java.awt.Font("Times New Roman", 0, 24));
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Car Model" }));
        Car_Model_Combo.setEnabled(false);
        Car_Model_Combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Car_Model_ComboActionPerformed(evt);
            }
        });
        getContentPane().add(Car_Model_Combo);
        Car_Model_Combo.setBounds(560, 120, 370, 50);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 230, 480, 380);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(null);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField3.setToolTipText("Flat/House No , Floor, Building ");
        jPanel1.add(jTextField3);
        jTextField3.setBounds(30, 50, 250, 30);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField4.setToolTipText("Colony/Society, Street, Locality/Area ");
        jPanel1.add(jTextField4);
        jTextField4.setBounds(30, 110, 250, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Town/City");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 160, 140, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("Address Line 1");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 30, 150, 15);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField5.setToolTipText("Enter city in which your house comes");
        jPanel1.add(jTextField5);
        jTextField5.setBounds(30, 180, 250, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Address Line 2");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 90, 160, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("State");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 230, 160, 15);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField6.setToolTipText("Enter state name");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(30, 250, 250, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel10.setText("PinCode");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 300, 150, 15);

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTextField7.setToolTipText("Enter pincode of your area");
        jPanel1.add(jTextField7);
        jTextField7.setBounds(30, 320, 250, 30);

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("Please hover over the");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(290, 20, 120, 14);

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("textbox to get info");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(290, 40, 100, 14);

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("about what to fill !!");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(290, 60, 100, 14);

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Not Mandatory !!");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 120, 90, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 230, 430, 380);

        Data_Addition.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        Data_Addition.setText("Confirm Purchase");
        Data_Addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Data_AdditionActionPerformed(evt);
            }
        });
        getContentPane().add(Data_Addition);
        Data_Addition.setBounds(130, 710, 360, 80);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cost (in Rs.) :");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(270, 640, 220, 40);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 36));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(480, 640, 320, 40);

        Main_Menu.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        Main_Menu.setText("Main Menu");
        Main_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Main_Menu);
        Main_Menu.setBounds(540, 710, 250, 80);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jButton5.setText("_");
        jButton5.setBorder(null);
        jButton5.setIconTextGap(0);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(870, 0, 40, 30);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jButton6.setText("X");
        jButton6.setBorder(null);
        jButton6.setIconTextGap(0);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(930, 0, 40, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/black-and-white-wallpaper-designs.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-480, 0, 1630, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Car model selection setup
    //Car model selection setup
    //Car model selection setup   
    private void Company_ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Company_ComboActionPerformed
  try {
            InputStream in = new FileInputStream("build\\classes\\tilefallOLD.wav");
            AudioStream as = new AudioStream(in);
            AudioPlayer.player.start(as);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


int n = Company_Combo.getSelectedIndex();
   if(n==1)
   {
     Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","DB9"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//aston.png"));
   }
   else
       if(n==2)
       {
        Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","A3 3.2 quattro","A4 3.2 FSI quattro","TT 3.2 quattro"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//audi.png"));
       }
   else
       if(n==3)
       {
         Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","M3 GTR"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//bmw.png"));
       }
   else
       if(n==4)
       {
          Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","CTS"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//cadillac.png"));
       }
   else
       if(n==5)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","Camaro SS","Cobalt SS","Corvette C6","Corvette C6.R"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//chevrolet.png"));
       }
   else
       if(n==6)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","Viper SRT-10"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//dodge.png"));
       }
   else
       if(n==7)
       {
          Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","Grande Punto"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//fiat.png"));
       }
   else
       if(n==8)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","Mustang GT","GT"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//ford.png"));
       }
   else
       if(n==9)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","Gallardo","Murciélago"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//lamb.png"));
       }
   else
       if(n==10)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","IS 300"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//lexus.png"));
       }
   else
       if(n==11)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","Elise"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//lotus.png"));
       }
   else
       if(n==12)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","RX-7 FD","RX-8"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//mazda.png"));
       }
   else
       if(n==13)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","CLK 500","SL 500","SL 65 AMG","SLR McLaren"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//benz.png"));
       }
   else
       if(n==14)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","Eclipse GT","Lancer Evolution VIII"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//mitsubishi.png"));
       }
   else
       if(n==15)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","GTO"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//pontiac.png"));
       }
   else
       if(n==16)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","911 Carrera S","911 GT2","911 Turbo S","Carrera GT","Cayman S"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//porsche.png"));
       }
   else
       if(n==17)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","Clio V6"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//renault.png"));
       }
   else
       if(n==18)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","Impreza WRX STi"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//subaru.png"));
       }
   else
       if(n==19)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","Supra"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//toyota.png"));
       }
   else
       if(n==20)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","Monaro VXR"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//vauxhall.png"));
       }
   else
       if(n==21)
       {
           Car_Model_Combo.setEnabled(true);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model","Golf GTI"}));

        jLabel4.setIcon(new ImageIcon("build\\classes//images//volkswagen.png"));
       }
   else
       {
           Car_Model_Combo.setEnabled(false);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model",""}));

        jLabel4.setIcon(new ImageIcon(""));
       }

    }//GEN-LAST:event_Company_ComboActionPerformed
    
    //Car cost setup
    //Car cost setup
    //Car cost setup
    private void Car_Model_ComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Car_Model_ComboActionPerformed
       try {
            InputStream in = new FileInputStream("build\\classes\\tilefallOLD.wav");
            AudioStream as = new AudioStream(in);
            AudioPlayer.player.start(as);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }


     int n = Company_Combo.getSelectedIndex();
     int m = Car_Model_Combo.getSelectedIndex();

     if(n==0)
     {
        Car_Model_Combo.setEnabled(false);
        Car_Model_Combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Select Car Model"}));
        jLabel15.setText("");
        jLabel4.setIcon(new ImageIcon(""));
     }


     else if(n==1)//aston martin
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;
            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Aston Martin DB9.gif"));
                     jLabel15.setText("5400000");
                     jLabel4.setVisible(true);
                     sound();
                break;
        }
     }


          else if(n==2)//audi
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Audi A3.gif"));
                     jLabel15.setText("1920000");
                     sound();
                break;

            case 2 : jLabel4.setIcon(new ImageIcon("build\\classes//Audi A4.gif"));
                     jLabel15.setText("2100000");
                     sound();
               break;

            case 3 : jLabel4.setIcon(new ImageIcon("build\\classes//Audi TT.gif"));
                     jLabel15.setText("2100000");
                     sound();
                break;

        }
     }



          else if(n==3)//BMW
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//BMW M3 GTR.gif"));
                     jLabel15.setText("7800000");
                     sound();
                break;

        }
     }



          else if(n==4)//cadillac
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Cadillac CTS.gif"));
                     jLabel15.setText("1920000");
                     sound();
                break;

        }
     }




          else if(n==5)//chevrolet
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Chevrolet Camaro SS.gif"));
                     jLabel15.setText("1800000");
                break;

            case 2 : jLabel4.setIcon(new ImageIcon("build\\classes//Chevrolet Cobalt.gif"));
                     jLabel15.setText("1560000");
                     sound();
                break;

            case 3 : jLabel4.setIcon(new ImageIcon("build\\classes//Chevrolet Corvette C6.gif"));
                     jLabel15.setText("4800000");
                     sound();
                break;

            case 4 : jLabel4.setIcon(new ImageIcon("build\\classes//Chevrolet Corvette C6.R.gif"));
                     jLabel15.setText("6000000");
                     sound();
                break;

        }
     }




          else if(n==6)//dodge
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Dodge Viper SRT.gif"));
                     jLabel15.setText("5880000");
                     sound();
                break;

        }
     }




          else if(n==7)//fiat
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Fiat Punto.gif"));
                     jLabel15.setText("1620000");
                     sound();
                break;

        }
     }



          else if(n==8)//ford
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Ford Mustang GT.gif"));
                     jLabel15.setText("2160000");
                     sound();
                break;

            case 2 : jLabel4.setIcon(new ImageIcon("build\\classes//Ford GT.gif"));
                     jLabel15.setText("16200000");
                     sound();
                break;

        }
     }




          else if(n==9)//LAMBORGHINI
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//gallardo.gif"));
                     jLabel15.setText("30000000");
                     sound();
                break;

            case 2 : jLabel4.setIcon(new ImageIcon("build\\classes//murcielago.gif"));
                     jLabel15.setText("55000000");
                     sound();
                break;

        }
     }



          else if(n==10)//lexus
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Lexus IS 300.gif"));
                     jLabel15.setText("2500000");
                     sound();
                break;

        }
     }



          else if(n==11)//lotus
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Lotus Elise.gif"));
                     jLabel15.setText("3600000");
                     sound();
                break;

        }
     }




          else if(n==12)//mazda
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Mazda RX-7.gif"));
                     jLabel15.setText("4500000");
                     sound();
                break;

            case 2 : jLabel4.setIcon(new ImageIcon("build\\classes//Mazda RX-8.gif"));
                     jLabel15.setText("5000000");
                     sound();
                break;

        }
     }




          else if(n==13)//mercedec-benz
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Mercedez-Benz CLK 500.gif"));
                     jLabel15.setText("6800000");
                     sound();
                break;

            case 2 : jLabel4.setIcon(new ImageIcon("build\\classes//Mercedez-Benz SL 500.gif"));
                     jLabel15.setText("7000000");
                     sound();
                break;

            case 3 : jLabel4.setIcon(new ImageIcon("build\\classes//Mercedez-Benz SL65 AMG.gif"));
                     jLabel15.setText("7900000");
                     sound();
                break;

            case 4 : jLabel4.setIcon(new ImageIcon("build\\classes//Mercedez-Benz SLR McLaren.gif"));
                     jLabel15.setText("18000000");
                     sound();
                break;

        }
     }




          else if(n==14)//mitsubishi motors
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Mitsubishi Eclipse.gif"));
                     jLabel15.setText("3500000");
                     sound();
                break;

            case 2 : jLabel4.setIcon(new ImageIcon("build\\classes//Mitsubishi Lancer.gif"));
                     jLabel15.setText("3000000");
                     sound();
                break;

        }
     }





          else if(n==15)//pontiac
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Pontiac GTO.gif"));
                     jLabel15.setText("3000000");
                     sound();
                break;

        }
     }






          else if(n==16)//porsche
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Porsche 911 Carrera S.gif"));
                     jLabel15.setText("5500000");
                     sound();
                break;

            case 2 : jLabel4.setIcon(new ImageIcon("build\\classes//Porsche 911 GT 2.gif"));
                     jLabel15.setText("6500000");
                     sound();
                break;

            case 3 : jLabel4.setIcon(new ImageIcon("build\\classes//Porsche 911 Turbo S.gif"));
                     jLabel15.setText("6300000");
                     sound();
                break;

            case 4 : jLabel4.setIcon(new ImageIcon("build\\classes//Porsche 911 Carrera GT.gif"));
                     jLabel15.setText("45000000");
                     sound();
                break;

            case 5 : jLabel4.setIcon(new ImageIcon("build\\classes//Porsche 911 Cayman S.gif"));
                     jLabel15.setText("7600000");
                     sound();
                break;

        }
     }





          else if(n==17)//renault
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Renault Clio.gif"));
                     jLabel15.setText("3500000");
                     sound();
                break;

        }
     }






          else if(n==18)//subaru
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Subaru Impreza.gif"));
                     jLabel15.setText("4500000");
                     sound();
                break;

        }
     }




          else if(n==19)//toyota
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Toyota Supra.gif"));
                     jLabel15.setText("4500000");
                     sound();
                break;

        }
     }




          else if(n==20)//vauxhall
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Vauxhall Monaro VXR.gif"));
                     jLabel15.setText("3200000");
                     sound();
                break;

        }
     }





          else if(n==21)//volkswagen
     {
        switch(m)
        {
            case 0 : jLabel4.setIcon(null);
                     jLabel15.setText("");
                break;

            case 1 : jLabel4.setIcon(new ImageIcon("build\\classes//Volkswagon Golf GTI.gif"));
                     jLabel15.setText("2200000");
                     sound();
                break;

        }
     }
    }//GEN-LAST:event_Car_Model_ComboActionPerformed
    
    //Car specs window opener
    //Car specs window opener
    //Car specs window opener    
    //Addition of data to database
    //Addition of data to database
    //Addition of data to database
    private void Data_AdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Data_AdditionActionPerformed
try {
                     float phoneno = Float.parseFloat(jTextField2.getText());

                     } catch (Exception z) {
                         JOptionPane.showMessageDialog(this, "Incorrect phone number !!",
                            "Inane error", JOptionPane.ERROR_MESSAGE);
                         jTextField2.setText("");
                         return;
                }
try {
                     int pin = Integer.parseInt(jTextField7.getText());

                     } catch (Exception z) {
                         JOptionPane.showMessageDialog(this, "Incorrect PinCode !!",
                            "Inane error", JOptionPane.ERROR_MESSAGE);
                         jTextField2.setText("");
                         return;
                }
 String address;
     if(jTextField1.getText().equals("")||
        jTextField2.getText().equals("")||
        jTextField3.getText().equals("")||
        jTextField5.getText().equals("")||
        jTextField6.getText().equals("")||
        jTextField7.getText().equals(""))
     {
         JOptionPane.showMessageDialog(this,"Please fill in complete details !!","Error",JOptionPane.ERROR_MESSAGE);

        }
 else{
String name = jTextField1.getText();
String phone = jTextField2.getText();
if(jTextField4.getText().equals(""))
 address = jTextField3.getText()+","+jTextField5.getText()+","+jTextField6.getText()+","+jTextField7.getText();
else
 address = jTextField3.getText()+","+jTextField4.getText()+","+jTextField5.getText()+","+jTextField6.getText()+","+jTextField7.getText();
double cost = Double.parseDouble(jLabel15.getText());
String company = (String) Company_Combo.getSelectedItem();
String model = (String) Car_Model_Combo.getSelectedItem();
int row = 0;
Date date = null;


        try{
        Class.forName("java.sql.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/investigatory_project", "root", "beyblade");
        Statement stmt = conn.createStatement();
        String row_count = "SELECT COUNT(*) FROM cars";
        ResultSet rs1 = stmt.executeQuery(row_count);
        while(rs1.next())
        {
            row = rs1.getInt(1);
        }
        int nrow = 1 + row;
        String d = "SELECT CURDATE()";
        ResultSet rs2 = stmt.executeQuery(d);
        while(rs2.next())
        {
            date = rs2.getDate(1);
        }
        String query = "INSERT INTO cars VALUES("+
                nrow+",'"+
                name+"','"+
                company+"','"+
                model+"',"+
                cost+",'"+
                date+"','"+
                phone+"','"+
                address+"');";
        stmt.executeUpdate(query);

        JOptionPane.showMessageDialog(this, "Thank you for purchase");
        JOptionPane.showMessageDialog(this,"Your car will be delivered to the defined address as SOON as possible!!");
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
         Company_Combo.setEnabled(false);
         Car_Model_Combo.setEnabled(false);
         Data_Addition.setEnabled(false);
        int response = JOptionPane.showConfirmDialog(rootPane,"Purchase another car ??","What's Next ??", 1);
        if(response==JOptionPane.NO_OPTION)
        {
           int response2 =  JOptionPane.showConfirmDialog(rootPane,"Exit the applicaion ??","Then ??", 1);
           if(response2==JOptionPane.YES_OPTION)
           {
               System.exit(0);
           }
           if(response2==JOptionPane.NO_OPTION)
           {
               this.setVisible(false);
               new Main_Window().setVisible(true);
           }
        }
        if(response==JOptionPane.YES_OPTION)
        {
        this.setVisible(false);
        new Form().setVisible(true);
        }

        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());

        }
         try {
            InputStream in = new FileInputStream("build\\classes\\tilefallOLD.wav");
            AudioStream as = new AudioStream(in);
            AudioPlayer.player.start(as);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
    }//GEN-LAST:event_Data_AdditionActionPerformed
      
    //Back to main menu
    //Back to main menu
    //Back to main menu
    private void Main_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_MenuActionPerformed
this.setVisible(false);
new Main_Window().setVisible(true);
 try {
            InputStream in = new FileInputStream("build\\classes\\tilefallOLD.wav");
            AudioStream as = new AudioStream(in);
            AudioPlayer.player.start(as);
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_Main_MenuActionPerformed

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        jButton5.setBackground(Color.gray);
        jButton5.setForeground(Color.white); // TODO add your handling code here:
}//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setBackground(Color.white);
        jButton5.setForeground(Color.black); // TODO add your handling code here:
}//GEN-LAST:event_jButton5MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setExtendedState(this.getExtendedState() | Frame.ICONIFIED);
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        jButton6.setBackground(Color.red);
        jButton6.setForeground(Color.white);
}//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        jButton6.setBackground(Color.white);
        jButton6.setForeground(Color.black);// TODO add your handling code here:
}//GEN-LAST:event_jButton6MouseExited

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);        // TODO add your handling code here:
}//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Car_Model_Combo;
    private javax.swing.JComboBox Company_Combo;
    private javax.swing.JButton Data_Addition;
    private javax.swing.JButton Main_Menu;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
